Add header
torqbit/portfolio-website pull request #24
Opened 2024-01-12 21:32 UTC by srikant96

2024-01-13 15:34 UTC, amezng commented
Menu needs to be fixed

2024-01-13 15:36 UTC, amezng requested changes
Fix css for media query

2024-01-13 15:36 UTC, amezng commented on styles/header.css
> +    right: -300px;
No need of this

2024-01-13 15:52 UTC, amezng requested changes

2024-01-13 15:52 UTC, amezng commented on index.html
> +            <li><a href="#">About</a></li>
Use the section id in the href. For eg. `#about` , `#articles` and so on..

2024-01-13 15:52 UTC, amezng commented on styles/header.css
> +.hamburger{
Remove this code, and use span/div tag.

2024-01-13 15:53 UTC, amezng commented on styles/header.css
> +.hamburger{
set the z-index too

2024-01-15 12:12 UTC, srikant96 commented
resolved header section - close #26

2024-01-16 12:16 UTC, amezng commented
Don't use vs code

2024-01-16 12:16 UTC, closed without merging